name: Deploy Flask App

on:
  push:
    branches: [ "main" ]  # deploy only after merge

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: [self-hosted, Windows, X64]   #  use your runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Global-Value-Web
          password: ${{ secrets.CR_PAT }}

    
      - name: Build and push Docker image
        run: |
          $IMAGE_NAME="ghcr.io/global-value-web/MobileAppMediaUpload_app:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy on same server
        run: |
          $IMAGE_NAME="ghcr.io/global-value-web/MobileAppMediaUpload_app:latest"
          docker pull $IMAGE_NAME
          # Stop container if it exists
          if (docker ps -a -q -f name=MobileAppMediaUpload_app) {
             docker stop MobileAppMediaUpload_app
             docker rm MobileAppMediaUpload_app
          }
          docker run -d --restart=always -p 9096:9096 --name MobileAppMediaUpload_app -v C:/inetpub/viabl/deploymentServer2/apps/_scripts/Whatsapp/images:/app/uploads/images -v C:/inetpub/viabl/deploymentServer2/apps/_scripts/Whatsapp/audios:/app/uploads/audios -v C:/keys:/app/keys -e SECRET_KEY="${{ secrets.SECRET_KEY }}" $IMAGE_NAME